//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Join_Scholarship_Applicant
    {
        public int ID { get; set; }
        public int ScholarshipID { get; set; }
        public Nullable<int> AppID { get; set; }

        //public virtual scholarship scholarship { get; set; }
        //public virtual Student_Info Student_Info { get; set; }
    }
}
