//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scholarship
    {
        //public scholarship()
        //{
        //    this.Join_Department_Scholarship = new HashSet<Join_Department_Scholarship>();
        //    this.Join_Scholarship_Student = new HashSet<Join_Scholarship_Student>();
        //}

        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfRegisterStart { get; set; }
        public System.DateTime DateOfRegisterEnd { get; set; }
        public string Percentage { get; set; }
        public string Constraint { get; set; }
        public string AdditionalInfo{ get; set; }

    //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //public virtual ICollection<Join_Department_Scholarship> Join_Department_Scholarship { get; set; }
    //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //public virtual ICollection<Join_Scholarship_Student> Join_Scholarship_Student { get; set; }
}
}
