//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public University()
        //{
        //    this.Colleges = new HashSet<College>();
        //}

        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
      
        public System.DateTime DateOfCreate { get; set; }
        public string WebLink { get; set; }
    
        public string AdditionalInfo { get; set; }
        public string Image { get; set; }
        public string LanguageRequired { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<College> Colleges { get; set; }
    }
}
